# Generated by Django 4.1.6 on 2023-07-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pictures/')),
                ('description', models.TextField()),
            ],
        ),
    ]
