# Generated by Django 4.1.6 on 2023-07-30 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('secret_photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_image', models.BinaryField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='92e49abc531a497ba0ae53cff66a71ee', max_length=33),
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_key', models.CharField(max_length=33)),
                ('image_data', models.BinaryField()),
                ('photo_name', models.CharField(max_length=50)),
                ('description', models.BinaryField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(null=True)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
