# Generated by Django 4.1.6 on 2023-07-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_photo', '0002_alter_customuser_user_key_photogallery_cookieconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_image', models.BinaryField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_key',
            field=models.CharField(default='10b566f81daa422fa97f40f7ca7e4a59', max_length=33),
        ),
    ]
